# Generated by Django 4.2 on 2024-12-05 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='usuario',
            new_name='usuario_id',
        ),
    ]
